### ISSUE TITLE
| BMP | DST1AS | Incorrect Information |

### ISSUE THREAD

**Issue by marcelobalbinot** [akvorado/akvorado#1325] opened 2024-07-26 15:24 UTC
Hi,

We use BMP to deliver routing information to Akvorado,

And we noticed the following scenario:

We received the prefix
aaa.bbb.144.0/21 with the following AS-PATH 54321 1234 i

And, we received the following more specific prefixes
aaa.bbb.144.0/22, aaa.bbb.148.0/22 ​​with the following AS-PATH 1234 i

So, no traffic destined to the prefix aaa.bbb.144.0/21 is forwarded through ASN 54321

But, Akvorado is adding DST1AS = 54321
to the flows whose destination ip is any ip from the prefix aaa.bbb.144.0/21. So, it is ignoring the more specific prefixes in the routing table and delivering incorrect information.

I would like to understand if this is in fact a problem or a configuration error on our side.

**Comment by vincentbernat** [comment] 2024-07-26 16:48
Duplicate of #1324.

**Closed by vincentbernat** 2024-07-26 16:48 UTC
Labels: bug
